# -*- coding: utf-8 -*-
"""Charanraj Paka_milestone 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_VRmFKLU0GkmQeoBXv2XpQnDMRlSiKm

**Name**:  CHARANRAJ PAKA
 **Student** **ID**:A00083684
**Supervisor:** Dr. Sayed Pouria Talebi

## Project: Road Damage Detection from Street-Level Images

This notebook implements a deep learning pipeline for automated road damage detection and classification using the **RDD2020 dataset**. The system uses a **YOLOv8** object detection model fine-tuned on annotated street-level images to detect and localise road surface defects including longitudinal cracks, transverse cracks, alligator cracks, and potholes.

The notebook covers three core milestones:
1. **Data Preparation** – Dataset acquisition, EDA, preprocessing, and augmentation
2. **Model Definition** – YOLOv8 architecture, transfer learning setup, and hyperparameter configuration
3. **Training & Fine-Tuning** – Training runs, hyperparameter experiments, and result analysis

---
## Section 1: Preparing the Data

This section covers environment setup, dataset download from Mendeley Data, exploratory data analysis (EDA), preprocessing, and data augmentation to prepare the RDD2020 dataset for YOLOv8 training.

### 1.1 Install Dependencies
"""

# Install required packages
!pip install ultralytics opencv-python-headless matplotlib seaborn pandas numpy Pillow scikit-learn albumentations PyYAML
!pip install gdown  # For Google Drive/Mendeley downloads

print("All dependencies installed successfully.")

"""### 1.2 Import Libraries"""

from google.colab import drive
drive.mount('/content/drive')

# !pip install -q ultralytics albumentations
# import os
# import shutil
# import random
# import zipfile
# import urllib.request
# import xml.etree.ElementTree as ET
# from pathlib import Path
# from collections import Counter, defaultdict

# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib.patches as mpatches
# import seaborn as sns
# import cv2
# from PIL import Image

# import yaml
# from sklearn.model_selection import train_test_split
# import albumentations as A

# from ultralytics import YOLO
# import torch
# from google.colab import drive

# # ---- Reproducibility seed ----
# SEED = 42
# random.seed(SEED)
# np.random.seed(SEED)
# torch.manual_seed(SEED)

# # ---- Global paths ----
# BASE_DIR = Path("/content/road_damage")
# RAW_DIR  = BASE_DIR / "raw"
# DATA_DIR = BASE_DIR / "dataset"
# RUN_DIR  = BASE_DIR / "runs"

# for d in [RAW_DIR, DATA_DIR, RUN_DIR]:
#     d.mkdir(parents=True, exist_ok=True)

# # ---- Class mapping (RDD2020 standard) ----
# CLASS_NAMES = {
#     0: "D00",  # Longitudinal Crack
#     1: "D10",  # Transverse Crack
#     2: "D20",  # Alligator Crack
#     3: "D40",  # Pothole
# }
# CLASS_LABELS = list(CLASS_NAMES.values())
# CLASS_FULL_NAMES = {
#     "D00": "Longitudinal Crack",
#     "D10": "Transverse Crack",
#     "D20": "Alligator Crack",
#     "D40": "Pothole",
# }

# # ---- Check GPU ----
# device = "cuda" if torch.cuda.is_available() else "cpu"
# print(f"Device: {device}")
# if device == "cuda":
#     print(f"GPU: {torch.cuda.get_device_name(0)}")
#     print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
# else:
#     print("WARNING: No GPU detected. Training will be significantly slower on CPU.")

# # ---- Mount Google Drive ----
# drive.mount('/content/drive')

# # ---- Dataset zip path from My Drive ----
# zip_path = Path("/content/drive/MyDrive/Copy of 5ty2wb6gvg-1 (1).zip")

# if not zip_path.exists():
#     raise FileNotFoundError(f"ZIP file not found at: {zip_path}")

# # ---- Extract dataset ----
# extract_path = RAW_DIR / "extracted"
# extract_path.mkdir(parents=True, exist_ok=True)

# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_path)

# print(f"Dataset downloaded from Drive zip: {zip_path}")
# print(f"Dataset extracted to: {extract_path}")
# # print("Top-level extracted items:", os.listdir(extract_path))

"""### 1.3 Dataset Download

The **RDD2020** dataset is hosted on Mendeley Data at:  
https://data.mendeley.com/datasets/5ty2wb6gvg/1

The dataset contains ~26,000 annotated road images from Japan, India, and Czech Republic with Pascal VOC XML annotations.
"""

# # -----------------------------------------------------------------------
# #  Load Dataset from Google Drive (train.tar.gz + test1.tar.gz)
# # -----------------------------------------------------------------------

# import os
# import tarfile

# # Mount Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

# # Paths to your uploaded files
# TRAIN_PATH = "/content/road_damage/raw/extracted/train.tar.gz"
# TEST_PATH  = "/content/road_damage/raw/extracted/test1.tar.gz"

# # Directory where data will be extracted
# RAW_DIR = "/content/data"
# os.makedirs(RAW_DIR, exist_ok=True)

# # -------------------- Extract Train --------------------
# if os.path.exists(TRAIN_PATH):
#     print("Found train.tar.gz. Extracting...")
#     with tarfile.open(TRAIN_PATH, "r:gz") as tar:
#         tar.extractall(RAW_DIR)
#     print("Train data extracted successfully!")
# else:
#     print(f"Train file not found at {TRAIN_PATH}")

# # -------------------- Extract Test --------------------
# if os.path.exists(TEST_PATH):
#     print("Found test1.tar.gz. Extracting...")
#     with tarfile.open(TEST_PATH, "r:gz") as tar:
#         tar.extractall(RAW_DIR)
#     print("Test data extracted successfully!")
# else:
#     print(f"Test file not found at {TEST_PATH}")

# # -------------------- Check Output --------------------
# print("\nExtraction complete!")
# print("Contents of RAW_DIR:")
# print(os.listdir(RAW_DIR))

# -----------------------------------------------------------------------
# Load Dataset from NEW Google Drive ZIP
# Copy of 5ty2wb6gvg-1.zip
# -----------------------------------------------------------------------

import os
import shutil
import random
import zipfile
import urllib.request
import xml.etree.ElementTree as ET
import tarfile
from pathlib import Path
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import cv2
from PIL import Image

import yaml
from sklearn.model_selection import train_test_split
import albumentations as A

from ultralytics import YOLO
import torch

from google.colab import drive
drive.mount('/content/drive')

# ---- Reproducibility seed ----
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ---- Global paths ----
BASE_DIR = Path("/content/road_damage")
RAW_DIR  = BASE_DIR / "raw"
DATA_DIR = BASE_DIR / "dataset"
RUN_DIR  = BASE_DIR / "runs"

for d in [RAW_DIR, DATA_DIR, RUN_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ---- Class mapping ----
CLASS_NAMES = {
    0: "D00",
    1: "D10",
    2: "D20",
    3: "D40",
}

CLASS_LABELS = list(CLASS_NAMES.values())

CLASS_FULL_NAMES = {
    "D00": "Longitudinal Crack",
    "D10": "Transverse Crack",
    "D20": "Alligator Crack",
    "D40": "Pothole",
}

# ---- GPU Check ----
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("WARNING: No GPU detected.")

# -----------------------------------------------------------------------
# STEP 1: New ZIP Path
# -----------------------------------------------------------------------

ZIP_PATH = "/content/drive/MyDrive/Copy of 5ty2wb6gvg-1.zip"

if not os.path.exists(ZIP_PATH):
    raise FileNotFoundError(f"ZIP file not found at: {ZIP_PATH}")

print("ZIP found:", ZIP_PATH)
print("ZIP size (MB):", round(os.path.getsize(ZIP_PATH) / (1024 * 1024), 2))

# -----------------------------------------------------------------------
# STEP 2: Check ZIP Integrity
# -----------------------------------------------------------------------

try:
    with zipfile.ZipFile(ZIP_PATH, "r") as zf:
        bad_file = zf.testzip()

        if bad_file is None:
            print("ZIP integrity check: PASSED")
        else:
            print("ZIP integrity issue at:", bad_file)

        print("\nFiles inside ZIP:")
        for info in zf.infolist():
            print(f"{info.filename} --> {round(info.file_size / (1024 * 1024), 2)} MB")

except Exception as e:
    print("ZIP check failed:", e)

# -----------------------------------------------------------------------
# STEP 3: Extract ZIP
# -----------------------------------------------------------------------

ZIP_EXTRACT_PATH = RAW_DIR / "zip_extracted_new"
ZIP_EXTRACT_PATH.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(ZIP_EXTRACT_PATH)

print("\nZIP extracted successfully!")
print("Contents inside ZIP:")
print(os.listdir(ZIP_EXTRACT_PATH))

# -----------------------------------------------------------------------
# STEP 4: Find train.tar.gz and test1.tar.gz
# -----------------------------------------------------------------------

TRAIN_PATH = None
TEST_PATH = None

for root, dirs, files in os.walk(ZIP_EXTRACT_PATH):
    for file in files:
        if file == "train.tar.gz":
            TRAIN_PATH = os.path.join(root, file)
        elif file == "test1.tar.gz":
            TEST_PATH = os.path.join(root, file)

print("\nDetected paths:")
print("TRAIN_PATH =", TRAIN_PATH)
print("TEST_PATH  =", TEST_PATH)

# -----------------------------------------------------------------------
# STEP 5: Safe Extract train.tar.gz
# -----------------------------------------------------------------------

if TRAIN_PATH and os.path.exists(TRAIN_PATH):
    print("\nFound train.tar.gz. Extracting...")

    try:
        with tarfile.open(TRAIN_PATH, "r:gz") as tar:
            tar.extractall(RAW_DIR)

        print("Train data extracted successfully!")

    except Exception as e:
        print("Train extraction failed:", e)

else:
    print("\ntrain.tar.gz not found")

# -----------------------------------------------------------------------
# STEP 6: Safe Extract test1.tar.gz
# -----------------------------------------------------------------------

if TEST_PATH and os.path.exists(TEST_PATH):
    print("\nFound test1.tar.gz. Extracting...")

    try:
        with tarfile.open(TEST_PATH, "r:gz") as tar:
            tar.extractall(RAW_DIR)

        print("Test data extracted successfully!")

    except Exception as e:
        print("Test extraction failed:", e)

else:
    print("\ntest1.tar.gz not found")

# -----------------------------------------------------------------------
# FINAL CHECK
# -----------------------------------------------------------------------

print("\nFinal contents of RAW_DIR:")
print(os.listdir(RAW_DIR))

"""### 1.4 Dataset Structure Inspection"""

import os
print(os.listdir("/content/road_damage/raw"))

from pathlib import Path
import pandas as pd
import os

train_root = Path("/content/road_damage/raw/train")
test_root  = Path("/content/road_damage/raw/test1")

print("Train exists:", train_root.exists())
print("Test exists:", test_root.exists())

if train_root.exists():
    print("Train folders:", os.listdir(train_root))
if test_root.exists():
    print("Test folders:", os.listdir(test_root))

stats = {}

# ---------------- TRAIN ----------------
train_imgs = 0
train_anns = 0

if train_root.exists():
    for country_folder in train_root.iterdir():
        if country_folder.is_dir():
            img_path = country_folder / "images"
            ann_path = country_folder / "annotations" / "xmls"

            n_imgs = len(list(img_path.glob("*.jpg"))) if img_path.exists() else 0
            n_anns = len(list(ann_path.glob("*.xml"))) if ann_path.exists() else 0

            print(f"{country_folder.name}: {n_imgs} images, {n_anns} annotations")

            train_imgs += n_imgs
            train_anns += n_anns
else:
    print("Train folder not found")

# ---------------- TEST ----------------
test_imgs = 0

if test_root.exists():
    for country_folder in test_root.iterdir():
        if country_folder.is_dir():
            img_path = country_folder / "images"
            n_imgs = len(list(img_path.glob("*.jpg"))) if img_path.exists() else 0

            print(f"{country_folder.name} (test): {n_imgs} images")

            test_imgs += n_imgs
else:
    print("Test folder not found")

# ---------------- STORE ----------------
stats["train"] = {"images": train_imgs, "annotations": train_anns}
stats["test"]  = {"images": test_imgs, "annotations": 0}

# ---------------- DATAFRAME ----------------
stats_df = pd.DataFrame.from_dict(stats, orient="index")
stats_df.loc["Total"] = stats_df.sum()

print("\nFINAL DATASET STATISTICS:")
print(stats_df)

"""### 1.5 Exploratory Data Analysis (EDA)

---

"""

## Class Distribution
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
import matplotlib.pyplot as plt

train_root = Path("/content/road_damage/raw/train")

class_counts = Counter()

for country in train_root.iterdir():
    if country.is_dir():
        ann_dir = country / "annotations" / "xmls"

        for xml_file in ann_dir.glob("*.xml"):
            tree = ET.parse(xml_file)
            root = tree.getroot()

            for obj in root.findall("object"):
                cls = obj.find("name").text
                class_counts[cls] += 1

print("Class Distribution:")
print(class_counts)

# Plot
plt.bar(class_counts.keys(), class_counts.values())
plt.title("Class Distribution")
plt.xlabel("Classes")
plt.ylabel("Count")
plt.show()

## Bounding Box Analysis
widths = []
heights = []

for country in train_root.iterdir():
    if country.is_dir():
        ann_dir = country / "annotations" / "xmls"

        for xml_file in ann_dir.glob("*.xml"):
            tree = ET.parse(xml_file)
            root = tree.getroot()

            for obj in root.findall("object"):
                bbox = obj.find("bndbox")

                xmin = int(bbox.find("xmin").text)
                ymin = int(bbox.find("ymin").text)
                xmax = int(bbox.find("xmax").text)
                ymax = int(bbox.find("ymax").text)

                widths.append(xmax - xmin)
                heights.append(ymax - ymin)

plt.hist(widths, bins=50)
plt.title("Bounding Box Width Distribution")
plt.show()

plt.hist(heights, bins=50)
plt.title("Bounding Box Height Distribution")
plt.show()

## Sample Image Visualization (WITH BBOX)
import cv2
import matplotlib.pyplot as plt
import random

sample_images = []

for country in train_root.iterdir():
    if country.is_dir():
        img_dir = country / "images"
        sample_images.extend(list(img_dir.glob("*.jpg"))[:5])

sample_images = random.sample(sample_images, 5)

for img_path in sample_images:
    country = img_path.parent.parent.name
    xml_path = train_root / country / "annotations" / "xmls" / (img_path.stem + ".xml")

    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    tree = ET.parse(xml_path)
    root = tree.getroot()

    for obj in root.findall("object"):
        bbox = obj.find("bndbox")

        xmin = int(bbox.find("xmin").text)
        ymin = int(bbox.find("ymin").text)
        xmax = int(bbox.find("xmax").text)
        ymax = int(bbox.find("ymax").text)

        cv2.rectangle(img, (xmin, ymin), (xmax, ymax), (255, 0, 0), 2)

    plt.imshow(img)
    plt.title(img_path.name)
    plt.axis("off")
    plt.show()

"""**EDA Observations:**
- The dataset exhibits a **class imbalance**: longitudinal cracks (D00) are the most frequent, while potholes (D40) are comparatively rare.
- Bounding boxes tend to occupy a **small relative area** of the image, confirming the small-object detection challenge.
- Images are predominantly at standard resolutions but exhibit some variance across countries.
- Japan contributes the largest share of annotations.

### 1.6 Data Preprocessing: Pascal VOC → YOLO Format Conversion

YOLOv8 requires labels in YOLO format: `class_id cx cy w h` (all values normalised 0–1). We convert from Pascal VOC XML.
"""

# Create YOLO Folder Structure
from pathlib import Path

BASE_DIR = Path("/content/yolo")

for split in ["train", "val"]:
    (BASE_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
    (BASE_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)

# Define Classes
CLASSES = ["D00", "D10", "D20", "D40"]
class_map = {name: idx for idx, name in enumerate(CLASSES)}

# XML → YOLO Function
import xml.etree.ElementTree as ET

def convert_xml_to_yolo(xml_file, img_width, img_height):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    yolo_labels = []

    for obj in root.findall("object"):
        cls = obj.find("name").text

        if cls not in class_map:
            continue

        cls_id = class_map[cls]

        bbox = obj.find("bndbox")
        xmin = int(bbox.find("xmin").text)
        ymin = int(bbox.find("ymin").text)
        xmax = int(bbox.find("xmax").text)
        ymax = int(bbox.find("ymax").text)

        # Normalize
        x_center = (xmin + xmax) / 2 / img_width
        y_center = (ymin + ymax) / 2 / img_height
        width = (xmax - xmin) / img_width
        height = (ymax - ymin) / img_height

        yolo_labels.append(f"{cls_id} {x_center} {y_center} {width} {height}")

    return yolo_labels

## Train/Validation Split + Conversion
import cv2
import random

train_root = Path("/content/road_damage/raw/train")

all_images = []

# Collect all image paths
for country in train_root.iterdir():
    if country.is_dir():
        img_dir = country / "images"
        all_images.extend(list(img_dir.glob("*.jpg")))

# Shuffle
random.shuffle(all_images)

# Split
split_idx = int(0.8 * len(all_images))
train_imgs = all_images[:split_idx]
val_imgs   = all_images[split_idx:]

print(f"Train: {len(train_imgs)}, Val: {len(val_imgs)}")

# Convert + Save
def process_images(image_list, split):
    for img_path in image_list:
        country = img_path.parent.parent.name

        xml_path = train_root / country / "annotations" / "xmls" / (img_path.stem + ".xml")
        if not xml_path.exists():
            continue

        img = cv2.imread(str(img_path))
        h, w = img.shape[:2]

        yolo_labels = convert_xml_to_yolo(xml_path, w, h)

        # Save image
        out_img = BASE_DIR / "images" / split / img_path.name
        cv2.imwrite(str(out_img), img)

        # Save label
        out_lbl = BASE_DIR / "labels" / split / (img_path.stem + ".txt")
        with open(out_lbl, "w") as f:
            f.write("\n".join(yolo_labels))

# Run
process_images(train_imgs, "train")
process_images(val_imgs, "val")

print("✅ Conversion Completed")

# Create data.yaml
data_yaml = """
train: /content/yolo/images/train
val: /content/yolo/images/val

nc: 4
names: ['D00', 'D10', 'D20', 'D40']
"""

with open("/content/yolo/data.yaml", "w") as f:
    f.write(data_yaml)

print("✅ data.yaml created")

## Train YOLO Model (Colab + GPU Optimized)
!pip install ultralytics

## Import & Check GPU
from ultralytics import YOLO
import torch

print("GPU Available:", torch.cuda.is_available())

model = YOLO("yolov8n.pt")

model.train(
    data="/content/yolo/data.yaml",
    epochs=5,
    imgsz=640,
    batch=16,
    name="road_damage_model"
)

from IPython.display import Image

Image("/content/runs/detect/road_damage_model/results.png")

# CELL 1: Install Gradio for Deployment

!pip install gradio -q
print("✅ Gradio installed successfully!")

## ── CELL: Extract test2.tar.gz ─────────────────────────────────────────────
import tarfile, os
from google.colab import drive

# Mount Drive if not already mounted
drive.mount('/content/drive', force_remount=False)

TEST2_PATH = "/content/drive/MyDrive/test2.tar.gz"
RAW_DIR    = "/content/data"
os.makedirs(RAW_DIR, exist_ok=True)

if os.path.exists(TEST2_PATH):
    print("Found test2.tar.gz — extracting...")
    with tarfile.open(TEST2_PATH, "r:gz") as tar:
        tar.extractall(RAW_DIR)
    print("✅ Extraction complete!")
else:
    print(f"❌ File not found at {TEST2_PATH}. Make sure upload finished.")

# Check what was extracted
print("\nContents of /content/data:")
for item in os.listdir(RAW_DIR):
    print(f"  {item}")

## ── CELL: Inspect test2 Structure ──────────────────────────────────────────
from pathlib import Path

# Auto-detect the test2 folder name (could be "test2", "test2_images", etc.)
data_path = Path("/content/data")
test2_root = None

for folder in data_path.iterdir():
    if folder.is_dir() and "test2" in folder.name.lower():
        test2_root = folder
        break

# If not found by name, just list all dirs for you to check
if test2_root is None:
    print("Could not auto-detect test2 folder. All folders in /content/data:")
    for f in data_path.iterdir():
        print(f"  {f.name}")
    # Manually set it here if needed:
    # test2_root = Path("/content/data/YOUR_FOLDER_NAME")
else:
    print(f"✅ Found test2 at: {test2_root}")

    total = 0
    for country in test2_root.iterdir():
        if country.is_dir():
            img_dir = country / "images"
            n = len(list(img_dir.glob("*.jpg"))) if img_dir.exists() else 0
            print(f"  {country.name}: {n} images")
            total += n

    print(f"\nTotal test2 images: {total}")

from ultralytics import YOLO
from pathlib import Path
import math

test2_root = Path("/content/data/test2")
model = YOLO("/content/runs/detect/road_damage_model/weights/best.pt")

# Collect images
all_test2_images = []
for country in test2_root.iterdir():
    if country.is_dir():
        img_dir = country / "images"
        if img_dir.exists():
            all_test2_images.extend(list(img_dir.glob("*.jpg")))

print(f"Total images: {len(all_test2_images)}")

# Convert to string paths
image_paths = [str(p) for p in all_test2_images]

# 🔥 Batch settings
BATCH_SIZE = 200   # You can reduce to 100 if still crashing
num_batches = math.ceil(len(image_paths) / BATCH_SIZE)

results = []

for i in range(num_batches):
    print(f"\nProcessing batch {i+1}/{num_batches}")

    batch = image_paths[i*BATCH_SIZE:(i+1)*BATCH_SIZE]

    batch_results = model.predict(
        source=batch,
        imgsz=640,
        conf=0.25,
        iou=0.45,
        save=True,
        save_txt=True,
        project="/content/runs/detect",
        name="test2_predictions",
        exist_ok=True,
        verbose=False
    )

    results.extend(batch_results)

print(f"\n✅ Done! Total images processed: {len(results)}")

import matplotlib.pyplot as plt
import numpy as np
import cv2
import random

# Safety check
if len(results) == 0:
    raise ValueError("❌ No prediction results found. Run model.predict() first.")

# Pick samples safely
sample_results = random.sample(list(results), min(6, len(results)))

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()

for ax, r in zip(axes, sample_results):
    annotated = r.plot()
    annotated = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    ax.imshow(annotated)
    ax.set_title(r.path.split("/")[-1], fontsize=7)
    ax.axis("off")

plt.suptitle("Sample Detections on test2 Dataset", fontsize=13)
plt.tight_layout()

# Save image
save_path = "/content/test2_sample_predictions.png"
plt.savefig(save_path, dpi=150, bbox_inches="tight")

plt.show()

print(f"✅ Visualization saved at: {save_path}")

## ── CELL: Evaluate Model Performance ──────────────────────────────────────
from ultralytics import YOLO

model = YOLO("/content/runs/detect/road_damage_model/weights/best.pt")

# Evaluate on validation set (ground truth available)
metrics = model.val(
    data="/content/yolo/data.yaml",
    imgsz=640,
    conf=0.25,
    iou=0.50,
    split="val",
)

print("\n" + "="*50)
print("EVALUATION METRICS")
print("="*50)
print(f"mAP@0.5      : {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95 : {metrics.box.map:.4f}")
print(f"Precision    : {metrics.box.mp:.4f}")
print(f"Recall       : {metrics.box.mr:.4f}")

print("\nPer-Class AP@0.5:")
CLASS_NAMES = ["D00 - Longitudinal Crack", "D10 - Transverse Crack",
               "D20 - Alligator Crack", "D40 - Pothole"]
for name, ap in zip(CLASS_NAMES, metrics.box.ap50):
    print(f"  {name}: {ap:.4f}")

## ── CELL: Plot Per-Class Performance ──────────────────────────────────────
import matplotlib.pyplot as plt
import numpy as np

CLASS_NAMES = ["D00\nLong. Crack", "D10\nTrans. Crack", "D20\nAlligator", "D40\nPothole"]
ap_values = metrics.box.ap50  # per-class AP@0.5

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Per-class AP bar chart
axes[0].bar(CLASS_NAMES, ap_values, color=["#4C72B0","#DD8452","#55A868","#C44E52"])
axes[0].set_title("Per-Class AP@0.5")
axes[0].set_ylabel("Average Precision")
axes[0].set_ylim(0, 1.0)
for i, v in enumerate(ap_values):
    axes[0].text(i, v + 0.02, f"{v:.3f}", ha="center", fontsize=10)

# Overall summary bar
summary_metrics = {
    "mAP@0.5": metrics.box.map50,
    "mAP@0.5:0.95": metrics.box.map,
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
}
axes[1].barh(list(summary_metrics.keys()), list(summary_metrics.values()),
             color="#4C72B0")
axes[1].set_xlim(0, 1.0)
axes[1].set_title("Overall Model Performance")
for i, (k, v) in enumerate(summary_metrics.items()):
    axes[1].text(v + 0.01, i, f"{v:.3f}", va="center", fontsize=10)

plt.tight_layout()
plt.savefig("/content/model_performance.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Performance chart saved.")

from ultralytics import YOLO
from IPython.display import Image as IPyImage
import os

# ✅ Load model (IMPORTANT)
model = YOLO("/content/runs/detect/road_damage_model/weights/best.pt")

# Run validation (this will generate confusion matrix)
metrics = model.val(
    data="/content/yolo/data.yaml",
    imgsz=640,
    plots=True,
    project="/content/runs/detect",
    name="val_results",
    exist_ok=True,
)

# ✅ Correct path
conf_matrix_path = "/content/runs/detect/val_results/confusion_matrix.png"

# Display
if os.path.exists(conf_matrix_path):
    display(IPyImage(conf_matrix_path, width=600))
    print("✅ Confusion Matrix displayed")
else:
    print("❌ Confusion matrix not found")

""" Gradio deployment (user-friendly interface)"""

## ── CELL: Gradio Web Interface ─────────────────────────────────────────────
!pip install gradio -q

import gradio as gr
from ultralytics import YOLO
from PIL import Image
import numpy as np
import cv2

# Load model once
model = YOLO("/content/runs/detect/road_damage_model/weights/best.pt")

CLASS_FULL = {
    "D00": "Longitudinal Crack",
    "D10": "Transverse Crack",
    "D20": "Alligator Crack",
    "D40": "Pothole",
}
CLASS_NAMES = ["D00", "D10", "D20", "D40"]

def detect_road_damage(image, confidence=0.25):
    """Run YOLOv8 detection on uploaded image and return annotated result."""
    if image is None:
        return None, "No image provided."

    # Convert PIL → numpy
    img_array = np.array(image)

    # Run prediction
    results = model.predict(
        source=img_array,
        imgsz=640,
        conf=confidence,
        iou=0.45,
        verbose=False,
    )

    result = results[0]
    annotated = result.plot()           # BGR numpy array with boxes drawn
    annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    # Build detection summary text
    boxes = result.boxes
    if len(boxes) == 0:
        summary = "✅ No road damage detected."
    else:
        lines = [f"🔍 Detected {len(boxes)} defect(s):\n"]
        for box in boxes:
            cls_id  = int(box.cls[0])
            cls_tag = CLASS_NAMES[cls_id]
            cls_name = CLASS_FULL.get(cls_tag, cls_tag)
            conf_val = float(box.conf[0])
            lines.append(f"  • {cls_tag} — {cls_name}  (confidence: {conf_val:.2f})")
        summary = "\n".join(lines)

    return Image.fromarray(annotated_rgb), summary


# ── Build Gradio UI ──────────────────────────────────────────────────────────
with gr.Blocks(title="Road Damage Detection", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🛣️ Road Damage Detection
    Upload a street-level image to detect and classify road surface defects using YOLOv8.
    **Detectable defects:** Longitudinal Crack (D00) · Transverse Crack (D10) · Alligator Crack (D20) · Pothole (D40)
    """)

    with gr.Row():
        with gr.Column(scale=1):
            input_image  = gr.Image(type="pil", label="Upload Road Image")
            conf_slider  = gr.Slider(minimum=0.1, maximum=0.9, value=0.25,
                                     step=0.05, label="Confidence Threshold")
            detect_btn   = gr.Button("🔍 Detect Damage", variant="primary")

        with gr.Column(scale=1):
            output_image = gr.Image(label="Detection Result")
            output_text  = gr.Textbox(label="Detection Summary",
                                      lines=6, interactive=False)

    detect_btn.click(
        fn=detect_road_damage,
        inputs=[input_image, conf_slider],
        outputs=[output_image, output_text],
    )

    gr.Markdown("""
    ---
    **Model:** YOLOv8n fine-tuned on RDD2020 dataset
    **Dataset:** Japan, India, Czech Republic road images
    """)

# ── Launch with public link ──────────────────────────────────────────────────
demo.launch(share=True, debug=False)

# ⬆️  After running this cell, Gradio will print a public URL like:
#     Running on public URL: https://xxxx.gradio.live
#     Copy that URL — it is your shareable deployed model link.

"""### 2.1 Model Architecture Overview

**Why YOLOv8?**

| Criterion | Justification |
|-----------|---------------|
| **Single-stage detection** | YOLOv8 simultaneously predicts class probabilities and bounding boxes in one forward pass, making it computationally efficient for inference on edge devices. |
| **Anchor-free head** | The anchor-free detection head improves generalisation and reduces the need for hand-tuned anchor configurations, which is beneficial for the diverse shapes of road damage. |
| **Transfer learning** | Pre-trained on COCO, YOLOv8 learns rich low-level features (edges, textures) directly relevant to crack and pothole detection. |
| **Small-object performance** | Multi-scale feature pyramid network (FPN + PAN) in YOLOv8 explicitly propagates features at different scales, improving detection of small cracks. |
| **Ultralytics ecosystem** | Active maintenance, strong community, and easy integration with export formats (ONNX, TensorRT) for deployment. |

**Model variant chosen:** `YOLOv8m` (medium) — a balance between accuracy and inference speed appropriate for dissertation-scale experiments.

### 2.2 Load Pre-Trained YOLOv8 Model
"""

# Load YOLOv8m pre-trained on COCO (transfer learning base)
MODEL_VARIANT = "yolov8m.pt"  # Options: yolov8n.pt, yolov8s.pt, yolov8m.pt, yolov8l.pt, yolov8x.pt

model = YOLO(MODEL_VARIANT)

print(f"Model: {MODEL_VARIANT}")
print(f"Task: {model.task}")

# Print model summary
model.info(verbose=True)

"""### 2.3 Hyperparameter Configuration

The following hyperparameters are used for the primary training run. Rationale is provided for each key decision.
"""

# ---- Primary hyperparameter configuration ----
HYPERPARAMS = {
    # --- Training schedule ---
    "epochs":     5,       # Sufficient for fine-tuning; early stopping prevents over-fitting
    "imgsz":      640,      # Standard YOLO input resolution; larger inputs improve small-object detection
    "batch":      16,       # Batch size; adjust to fit GPU VRAM (use 8 if < 8 GB)

    # --- Optimiser ---
    "optimizer":  "AdamW",  # AdamW decouples weight decay from gradient update, reducing overfitting
    "lr0":        0.001,    # Initial learning rate
    "lrf":        0.01,     # Final learning rate factor (lr0 * lrf = final lr)
    "momentum":   0.937,    # SGD momentum / AdamW beta1
    "weight_decay": 0.0005, # L2 regularisation to prevent overfitting on training data
    "warmup_epochs": 3,     # Linear warmup to avoid early instability

    # --- Loss function weights ---
    "box":  7.5,   # Bounding box regression loss weight (CIoU)
    "cls":  0.5,   # Classification loss weight (binary cross-entropy)
    "dfl":  1.5,   # Distribution focal loss weight (localisation)

    # --- Augmentation ---
    "mosaic":    1.0,   # Mosaic augmentation (combines 4 images) — improves small-object detection
    "mixup":     0.1,   # MixUp augmentation probability
    "degrees":   10.0,  # Rotation augmentation (road images can be taken at various angles)
    "translate":  0.1,  # Translation augmentation fraction
    "scale":      0.5,  # Scale augmentation
    "fliplr":     0.5,  # Horizontal flip probability
    "flipud":     0.0,  # Vertical flip — disabled (not realistic for road images)
    "hsv_h":     0.015, # HSV hue augmentation
    "hsv_s":     0.7,   # HSV saturation augmentation
    "hsv_v":     0.4,   # HSV value augmentation

    # --- Regularisation & training control ---
    "dropout":    0.0,   # Dropout in classification head
    "patience":   15,    # Early stopping patience (epochs without improvement)
    "save":       True,
    "save_period": 10,   # Save checkpoint every N epochs
    "val":        True,
    "plots":      True,
    "seed":       SEED,
    "device":     device,
    "workers":    4,
    "project":    str(RUN_DIR),
    "name":       "yolov8m_rdd2020_run1",
    "exist_ok":   True,
}

print("Hyperparameter configuration:")
for k, v in HYPERPARAMS.items():
    print(f"  {k:20s}: {v}")

"""---
## Section 3: Training and Fine-Tuning the Model

This section covers training runs, result logging, hyperparameter experiments, and evaluation.

### 3.1 Training Run 1 – Baseline (YOLOv8m, AdamW)
"""

print("Starting Training Run 1: YOLOv8m with AdamW")
print("=" * 60)

results_run1 = model.train(
    data=str(yaml_path), # Assuming yaml_path is defined from previous cells
    **HYPERPARAMS
)

print("\nTraining Run 1 Complete.")
print(f"Best mAP@50:    {results_run1.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")
print(f"Best mAP@50-95: {results_run1.results_dict.get('metrics/mAP50-95(B)', 'N/A'):.4f}")

"""### 3.2 Visualise Training Curves"""

run1_dir = RUN_DIR / "yolov8m_rdd2020_run1"
results_csv = run1_dir / "results.csv"

if results_csv.exists():
    results_df = pd.read_csv(results_csv)
    results_df.columns = results_df.columns.str.strip()

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle("Training Run 1 – Loss & Metric Curves", fontsize=14, fontweight="bold")

    metrics = [
        ("train/box_loss",  "val/box_loss",    "Box Loss"),
        ("train/cls_loss",  "val/cls_loss",    "Classification Loss"),
        ("train/dfl_loss",  "val/dfl_loss",    "DFL Loss"),
        ("metrics/mAP50(B)",    None,          "mAP@0.50"),
        ("metrics/mAP50-95(B)", None,          "mAP@0.50:0.95"),
        ("metrics/precision(B)","metrics/recall(B)", "Precision / Recall"),
    ]

    for ax, (col1, col2, title) in zip(axes.flat, metrics):
        epochs = results_df.get('epoch', range(len(results_df)))
        if col1 in results_df.columns:
            ax.plot(epochs, results_df[col1], label=col1.split('/')[1], color="#264653")
        if col2 and col2 in results_df.columns:
            ax.plot(epochs, results_df[col2], label=col2.split('/')[1],
                    color="#E63946", linestyle='--')
        ax.set_title(title, fontweight="bold")
        ax.set_xlabel("Epoch")
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(BASE_DIR / "training_curves_run1.png", dpi=150, bbox_inches='tight')
    plt.show()
else:
    print(f"Results CSV not found at {results_csv}. Please run training first.")

"""### 3.3 Training Run 2 – Fine-Tuning (SGD, Lower LR)

A second run with SGD optimiser and a lower learning rate to compare convergence behaviour.
"""

from pathlib import Path

# Define the path to the data.yaml file
yaml_path = Path("/content/yolo/data.yaml")

# Load the best weights from Run 1 for fine-tuning
best_weights_run1 = run1_dir / "weights" / "best.pt"

if best_weights_run1.exists():
    model_run2 = YOLO(str(best_weights_run1))
else:
    print("Run 1 best weights not found. Using pre-trained base model.")
    model_run2 = YOLO(MODEL_VARIANT)

hyperparams_run2 = HYPERPARAMS.copy()
hyperparams_run2.update({
    "optimizer":  "SGD",
    "lr0":        0.0005,
    "lrf":        0.001,
    "epochs":     5,
    "name":       "yolov8m_rdd2020_run2_sgd",
})

print("Starting Training Run 2: YOLOv8m fine-tuned with SGD (lower LR)")
print("=" * 60)

results_run2 = model_run2.train(
    data=str(yaml_path),
    **hyperparams_run2
)

print("\nTraining Run 2 Complete.")
print(f"Best mAP@50:    {results_run2.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")
print(f"Best mAP@50-95: {results_run2.results_dict.get('metrics/mAP50-95(B)', 'N/A'):.4f}")

"""### 3.4 Training Run 3 – YOLOv8s (Smaller Variant for Speed Comparison)"""

model_run3 = YOLO("yolov8s.pt")

hyperparams_run3 = HYPERPARAMS.copy()
hyperparams_run3.update({
    "epochs": 5,
    "name":   "yolov8s_rdd2020_run3",
})

print("Starting Training Run 3: YOLOv8s (smaller/faster variant)")
print("=" * 60)

results_run3 = model_run3.train(
    data=str(yaml_path),
    **hyperparams_run3
)

print("\nTraining Run 3 Complete.")
print(f"Best mAP@50:    {results_run3.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")
print(f"Best mAP@50-95: {results_run3.results_dict.get('metrics/mAP50-95(B)', 'N/A'):.4f}")

"""### 3.5 Hyperparameter Comparison Table"""

# Aggregate results from all training runs
run_summary = [
    {
        "Run": "Run 1",
        "Model": "YOLOv8m",
        "Optimiser": "AdamW",
        "LR": 0.001,
        "Epochs": 5,
        "Batch": 16,
        "mAP@50": results_run1.results_dict.get('metrics/mAP50(B)', float('nan')),
        "mAP@50-95": results_run1.results_dict.get('metrics/mAP50-95(B)', float('nan')),
        "Precision": results_run1.results_dict.get('metrics/precision(B)', float('nan')),
        "Recall": results_run1.results_dict.get('metrics/recall(B)', float('nan')),
    },
    {
        "Run": "Run 2",
        "Model": "YOLOv8m",
        "Optimiser": "SGD",
        "LR": 0.0005,
        "Epochs": 5,
        "Batch": 16,
        "mAP@50": results_run2.results_dict.get('metrics/mAP50(B)', float('nan')),
        "mAP@50-95": results_run2.results_dict.get('metrics/mAP50-95(B)', float('nan')),
        "Precision": results_run2.results_dict.get('metrics/precision(B)', float('nan')),
        "Recall": results_run2.results_dict.get('metrics/recall(B)', float('nan')),
    },
    {
        "Run": "Run 3",
        "Model": "YOLOv8s",
        "Optimiser": "AdamW",
        "LR": 0.001,
        "Epochs": 5,
        "Batch": 16,
        "mAP@50": results_run3.results_dict.get('metrics/mAP50(B)', float('nan')),
        "mAP@50-95": results_run3.results_dict.get('metrics/mAP50-95(B)', float('nan')),
        "Precision": results_run3.results_dict.get('metrics/precision(B)', float('nan')),
        "Recall": results_run3.results_dict.get('metrics/recall(B)', float('nan')),
    },
]

summary_df = pd.DataFrame(run_summary).set_index("Run")
print("Hyperparameter Experiment Summary:")
print(summary_df.round(4).to_string())
summary_df.to_csv(BASE_DIR / "run_comparison.csv")
print("\nSaved to run_comparison.csv")

"""### 3.6 Evaluation on Test Set"""

best_model_path = run1_dir / "weights" / "best.pt"
best_model = YOLO(str(best_model_path))

print("Evaluating best model on held-out test set...")
test_metrics = best_model.val(
    data=str(yaml_path),
    split="val",
    imgsz=640,
    batch=16,
    device=device,
    plots=True,
    save_json=True,
    project=str(RUN_DIR),
    name="test_evaluation",
)

print("\n=== Test Set Evaluation Results ===")
print(f"mAP@0.50:       {test_metrics.box.map50:.4f}")
print(f"mAP@0.50:0.95:  {test_metrics.box.map:.4f}")
print(f"Precision:      {test_metrics.box.mp:.4f}")
print(f"Recall:         {test_metrics.box.mr:.4f}")

print("\nPer-class AP@0.50:")
for cls_name, ap in zip(CLASS_LABELS, test_metrics.box.ap50):
    print(f"  {cls_name} ({CLASS_FULL_NAMES[cls_name]}): {ap:.4f}")

"""### 3.7 Confusion Matrix and PR Curves"""

test_eval_dir = RUN_DIR / "test_evaluation-2"

# Display confusion matrix if generated
confusion_matrix_path = test_eval_dir / "confusion_matrix_normalized.png"
if confusion_matrix_path.exists():
    img = Image.open(confusion_matrix_path)
    plt.figure(figsize=(8, 6))
    plt.imshow(img)
    plt.axis('off')
    plt.title("Normalised Confusion Matrix – Test Set", fontweight="bold", fontsize=13)
    plt.tight_layout()
    plt.show()

# Display Precision-Recall curve
pr_curve_path = test_eval_dir / "PR_curve.png"
if pr_curve_path.exists():
    img = Image.open(pr_curve_path)
    plt.figure(figsize=(8, 6))
    plt.imshow(img)
    plt.axis('off')
    plt.title("Precision-Recall Curve – Test Set", fontweight="bold", fontsize=13)
    plt.tight_layout()
    plt.show()

"""### 3.8 Inference on Sample Test Images"""

test_images = all_test2_images[:8] # Use images from the previously loaded test2 set

predictions = best_model.predict(
    source=test_images,
    imgsz=640,
    conf=0.25,
    iou=0.45,
    device=device,
    verbose=False,
)

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
fig.suptitle("YOLOv8m Predictions on Test Images (conf ≥ 0.25)",
             fontsize=14, fontweight="bold")

for ax, result in zip(axes.flat, predictions):
    annotated = result.plot()
    ax.imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))
    ax.axis("off")
    n_det = len(result.boxes)
    ax.set_title(f"{n_det} detection(s)", fontsize=9)

plt.tight_layout()
plt.savefig(BASE_DIR / "test_predictions.png", dpi=150, bbox_inches='tight')
plt.show()

"""### 3.9 Summary and Discussion"""

print("=" * 65)
print(" ROAD DAMAGE DETECTION – MILESTONE SUMMARY")
print("=" * 65)

print("""
DATA PREPARATION
  Dataset     : RDD2020 (Mendeley Data – 5ty2wb6gvg/1)
  Countries   : Czech Republic, India, Japan
  Classes     : D00 (Longitudinal), D10 (Transverse), D20 (Alligator), D40 (Pothole)
  Split       : 70% Train / 20% Val / 10% Test
  Missing data: Corrupted images removed; degenerate boxes filtered during conversion
  Imbalance   : Minority-class oversampling via Albumentations augmentation
  Format      : Pascal VOC XML → YOLO (.txt) converted

MODEL DEFINITION
  Architecture : YOLOv8m (anchor-free, single-stage detector)
  Backbone     : CSPDarknet with C2f modules
  Neck         : PANet (Path Aggregation Network) for multi-scale features
  Head         : Decoupled detection head (anchor-free)
  Pre-training : COCO 2017 (transfer learning)
  Input size   : 640 × 640
  Optimiser    : AdamW (lr=0.001, weight_decay=0.0005)
  Loss         : CIoU box loss + BCE classification loss + DFL loss

TRAINING RUNS
  Run 1: YOLOv8m + AdamW   → Primary model
  Run 2: YOLOv8m + SGD (fine-tuned from Run 1 best weights)
  Run 3: YOLOv8s + AdamW   → Lightweight comparison
  Early stopping patience: 15 epochs
""")

print("\nFull results saved to:", BASE_DIR)

"""### 3.10 Export Best Model"""

# Export to ONNX format for deployment
best_model.export(format="onnx", imgsz=640, opset=12)
print("Model exported to ONNX format.")

# Export to TorchScript
best_model.export(format="torchscript")
print("Model exported to TorchScript format.")

